"""World package — state service and agent-facing read tools.

The world-read interface is wire-stable: new tables can join the surface;
existing reads never change shape.
"""

from __future__ import annotations

from world.errors import (
    AfterSalesReferenceRejected,
    CatalogMutationRejected,
    DisputeNotActionable,
    ExchangeNotActionable,
    FulfillmentNotActionable,
    IdempotencyConflict,
    IdempotencyReplay,
    InsufficientFunds,
    InvalidOrderTransition,
    LogicalTimeError,
    LifecycleAuthorizationError,
    OrderIdentityMismatch,
    OrderNotRefundable,
    OrderNotSettleable,
    OutOfStock,
    PartitionRead,
    TableNotFound,
    ReturnWindowClosed,
    ShipmentNotActionable,
    WorldError,
    WriteNotAuthorized,
)
from world.interfaces import (
    CatalogReader,
    DisputeReader,
    InventoryReader,
    LedgerReader,
    ReputationReader,
    RulingReader,
    SnapshotReader,
)
from world.catalog_mutations import CatalogMutationIntent
from world.negotiations import NegotiationIntent
from world.match_authorizations import (
    MatchAuthorizationChain,
    MatchAuthorizationFixture,
    issue_order_match_authorization,
)
from world.client import VCPWorldClient
from world.reset import E0Reset, E1Reset, ResetStrategy
from world.service import WorldService
from world.state import World
from world.store import DatabaseWorld, SQLiteWorldStore
from world.tools import WorldTools
from world.types import (
    AgentId,
    AllocationBatch,
    CartLine,
    CartQuote,
    Dispute,
    DisputeId,
    DisputeState,
    Exchange,
    ExchangeId,
    Friendship,
    FulfillmentAllocation,
    FeeComponent,
    InventoryRow,
    Listing,
    Money,
    Order,
    OrderGroup,
    OrderGroupId,
    OrderId,
    OrderState,
    OrderTimeline,
    Receipt,
    ReputationScore,
    Review,
    ReviewId,
    Ruling,
    RulingId,
    SkuId,
    Shipment,
    ShipmentId,
    ShipmentResolution,
    ShipmentStatus,
    ShipmentStatusEvent,
    SupplyEventRecord,
    SupplyState,
    QuoteId,
    TxnId,
    WorldSnapshot,
)

__all__ = [
    "AgentId",
    "AfterSalesReferenceRejected",
    "AllocationBatch",
    "CartLine",
    "CartQuote",
    "CatalogReader",
    "CatalogMutationRejected",
    "CatalogMutationIntent",
    "Dispute",
    "DisputeId",
    "DisputeNotActionable",
    "DisputeReader",
    "DisputeState",
    "DatabaseWorld",
    "Exchange",
    "ExchangeId",
    "ExchangeNotActionable",
    "Friendship",
    "FulfillmentAllocation",
    "FeeComponent",
    "FulfillmentNotActionable",
    "E0Reset",
    "E1Reset",
    "IdempotencyConflict",
    "IdempotencyReplay",
    "InsufficientFunds",
    "InvalidOrderTransition",
    "LogicalTimeError",
    "InventoryReader",
    "InventoryRow",
    "LedgerReader",
    "Listing",
    "LifecycleAuthorizationError",
    "Money",
    "MatchAuthorizationChain",
    "MatchAuthorizationFixture",
    "NegotiationIntent",
    "Order",
    "OrderGroup",
    "OrderGroupId",
    "OrderIdentityMismatch",
    "OrderId",
    "OrderNotRefundable",
    "OrderNotSettleable",
    "OrderState",
    "OrderTimeline",
    "OutOfStock",
    "PartitionRead",
    "Receipt",
    "QuoteId",
    "ReputationReader",
    "ReputationScore",
    "ResetStrategy",
    "ReturnWindowClosed",
    "ShipmentNotActionable",
    "Review",
    "ReviewId",
    "Ruling",
    "RulingId",
    "RulingReader",
    "SkuId",
    "Shipment",
    "ShipmentId",
    "ShipmentResolution",
    "ShipmentStatus",
    "ShipmentStatusEvent",
    "SupplyEventRecord",
    "SupplyState",
    "SQLiteWorldStore",
    "SnapshotReader",
    "TableNotFound",
    "TxnId",
    "VCPWorldClient",
    "World",
    "WorldError",
    "WorldService",
    "WorldSnapshot",
    "WorldTools",
    "WriteNotAuthorized",
    "issue_order_match_authorization",
]
