"""Episode package — the thin scenario-lifecycle wrapper.

The scenario file shape and the report shape are wire-stable: fields can be
added, never removed or renamed. ``ScenarioLoader`` is the seam a future
``src/scenarios/`` package can plug into without touching ``Episode``.
"""

from __future__ import annotations

from episode.errors import EpisodeError, KickoffMissing, ScenarioInvalid, TerminalNotReached
from episode.benchmark import (
    BenchmarkMetadata,
    BenchmarkTrack,
    CatalogScale,
    CatalogSource,
    Difficulty,
    TaskFamily,
)
from episode.interfaces import AgentBuilder, Oracle, ScenarioLoader
from episode.catalog_provenance import (
    CatalogProvenanceMismatch,
    load_catalog_provenance,
    verify_catalog_provenance,
)
from episode.extensions import (
    MARKET_METRICS,
    ORACLE_PRIMITIVES,
    PLATFORM_POLICIES,
    SCENARIO_GENERATORS,
    WORLD_EVENT_HANDLERS,
    ExtensionRegistry,
    extension_manifest,
)
from episode.extension_runtime import (
    ExtensionEvaluationContext,
    ExtensionEvaluationExecution,
    ExtensionExecutionError,
    WorldEventExecution,
    apply_registered_world_events,
    evaluate_registered_extensions,
    write_extension_artifact,
)
from episode.runner import Episode, EpisodeBatch
from episode.scale import (
    SCALE_PROVENANCE_SCHEMA,
    SCALE_RUN_MANIFEST_SCHEMA,
    SCALE_SUITE_SCHEMA,
    SCALE_WORKLOAD_SCHEMA,
    ScaleConfig,
    ScaleProbeResult,
    ScaleReplayError,
    build_scale_run_manifest,
    build_scale_suite_manifest,
    collect_scale_environment,
    collect_scale_provenance,
    generate_sparse_market,
    replay_scale_event_log,
    run_scale_probe,
    scale_evidence_boundary,
    scale_file_descriptor,
    scale_workload_definition,
)
from episode.replay import (
    REPLAY_REPORT_SCHEMA,
    ReplayVerificationError,
    ReplayVerificationResult,
    ScaleBundleVerificationResult,
    resolve_replay_targets,
    verify_episode_replay,
    verify_replay_target,
    verify_scale_artifact_bundle,
    verify_scale_replay,
)
from episode.scenario import (
    build_agents,
    from_yaml,
    kickoff_envelope,
    kickoff_envelopes,
    load_all,
    population_for_scenario,
)
from episode.types import (
    BatchSpec,
    BuyerSpec,
    ControlServiceSpec,
    ExtensionEvaluationSpec,
    MerchantSpec,
    PopulationSpec,
    Report,
    RunMetadata,
    ScenarioSpec,
    WorldEventSpec,
)

__all__ = [
    "AgentBuilder",
    "BenchmarkMetadata",
    "BenchmarkTrack",
    "BatchSpec",
    "BuyerSpec",
    "ControlServiceSpec",
    "CatalogScale",
    "CatalogSource",
    "CatalogProvenanceMismatch",
    "Difficulty",
    "Episode",
    "EpisodeBatch",
    "EpisodeError",
    "ExtensionEvaluationContext",
    "ExtensionEvaluationExecution",
    "ExtensionEvaluationSpec",
    "ExtensionExecutionError",
    "ExtensionRegistry",
    "KickoffMissing",
    "MerchantSpec",
    "MARKET_METRICS",
    "Oracle",
    "ORACLE_PRIMITIVES",
    "PLATFORM_POLICIES",
    "PopulationSpec",
    "Report",
    "RunMetadata",
    "SCALE_RUN_MANIFEST_SCHEMA",
    "SCALE_PROVENANCE_SCHEMA",
    "SCALE_SUITE_SCHEMA",
    "SCALE_WORKLOAD_SCHEMA",
    "ScaleConfig",
    "ScaleBundleVerificationResult",
    "ScaleProbeResult",
    "ScaleReplayError",
    "ScenarioInvalid",
    "ScenarioLoader",
    "ScenarioSpec",
    "SCENARIO_GENERATORS",
    "TerminalNotReached",
    "TaskFamily",
    "WORLD_EVENT_HANDLERS",
    "WorldEventExecution",
    "WorldEventSpec",
    "apply_registered_world_events",
    "build_agents",
    "build_scale_run_manifest",
    "build_scale_suite_manifest",
    "collect_scale_environment",
    "collect_scale_provenance",
    "from_yaml",
    "generate_sparse_market",
    "extension_manifest",
    "evaluate_registered_extensions",
    "kickoff_envelope",
    "kickoff_envelopes",
    "load_all",
    "load_catalog_provenance",
    "population_for_scenario",
    "replay_scale_event_log",
    "REPLAY_REPORT_SCHEMA",
    "ReplayVerificationError",
    "ReplayVerificationResult",
    "resolve_replay_targets",
    "verify_episode_replay",
    "verify_catalog_provenance",
    "verify_replay_target",
    "verify_scale_replay",
    "run_scale_probe",
    "scale_evidence_boundary",
    "scale_file_descriptor",
    "scale_workload_definition",
    "verify_scale_artifact_bundle",
    "write_extension_artifact",
]
